export const initialDoctors = [
  {
    "id": "D001",
    "name": "Dr. Karthik G",
    "specialization": "Cardiology",
    "status": "On Duty",
    "contact": "Ext 401"
  },
  {
    "id": "D002",
    "name": "Dr. Gowshik Ram",
    "specialization": "Gynaecology",
    "status": "On Duty",
    "contact": "Ext 402"
  },
  {
    "id": "D003",
    "name": "Dr. Shyam Sundar",
    "specialization": "Urology",
    "status": "Off Duty",
    "contact": "Ext 403"
  },
  {
    "id": "D004",
    "name": "Dr. Arun Kumar",
    "specialization": "Oncology",
    "status": "On Duty",
    "contact": "Ext 404"
  },
  {
    "id": "D005",
    "name": "Dr. Garcia",
    "specialization": "Pediatrics",
    "status": "On Duty",
    "contact": "Ext 405"
  }
];

export const initialNurses = [
  {
    "id": "N001",
    "name": "Sarah Jenkins",
    "shift": "Morning",
    "status": "On Duty",
    "contact": "Ext 501"
  },
  {
    "id": "N002",
    "name": "Mike Ross",
    "shift": "Night",
    "status": "On Duty",
    "contact": "Ext 502"
  },
  {
    "id": "N003",
    "name": "Nancy Drew",
    "shift": "Morning",
    "status": "Off Duty",
    "contact": "Ext 503"
  },
  {
    "id": "N004",
    "name": "David Kim",
    "shift": "Night",
    "status": "On Duty",
    "contact": "Ext 504"
  },
  {
    "id": "N005",
    "name": "Emma Wilson",
    "shift": "Morning",
    "status": "On Duty",
    "contact": "Ext 505"
  },
  {
    "id": "N006",
    "name": "James Miller",
    "shift": "Night",
    "status": "Off Duty",
    "contact": "Ext 506"
  },
  {
    "id": "N007",
    "name": "Olivia Davis",
    "shift": "Morning",
    "status": "On Duty",
    "contact": "Ext 507"
  },
  {
    "id": "N008",
    "name": "William Moore",
    "shift": "Night",
    "status": "On Duty",
    "contact": "Ext 508"
  },
  {
    "id": "N009",
    "name": "Sophia Taylor",
    "shift": "Morning",
    "status": "Off Duty",
    "contact": "Ext 509"
  },
  {
    "id": "N010",
    "name": "Lucas Anderson",
    "shift": "Night",
    "status": "On Duty",
    "contact": "Ext 510"
  }
];

export const initialPatients = [
  {
    "id": "P001",
    "name": "Jane Smith",
    "age": 45,
    "room": "101B",
    "doctor": "Dr. Adams",
    "nurse": "Mike Ross",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 71,
    "spo2": 97,
    "rr": 17,
    "bp": "111/71",
    "emotion": "Neutral"
  },
  {
    "id": "P002",
    "name": "Robert Johnson",
    "age": 52,
    "room": "102C",
    "doctor": "Dr. Lee",
    "nurse": "Nancy Drew",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 72,
    "spo2": 98,
    "rr": 18,
    "bp": "112/72",
    "emotion": "Neutral"
  },
  {
    "id": "P003",
    "name": "Emily Davis",
    "age": 29,
    "room": "103D",
    "doctor": "",
    "nurse": "David Kim",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 73,
    "spo2": 99,
    "rr": 19,
    "bp": "113/73",
    "emotion": "Neutral"
  },
  {
    "id": "P004",
    "name": "Michael Brown",
    "age": 61,
    "room": "104A",
    "doctor": "Dr. Garcia",
    "nurse": "",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 74,
    "spo2": 96,
    "rr": 16,
    "bp": "114/74",
    "emotion": "Neutral"
  },
  {
    "id": "P005",
    "name": "Sarah Wilson",
    "age": 34,
    "room": "100B",
    "doctor": "Dr. Smith",
    "nurse": "James Miller",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 75,
    "spo2": 97,
    "rr": 17,
    "bp": "115/75",
    "emotion": "Neutral"
  },
  {
    "id": "P006",
    "name": "William Miller",
    "age": 47,
    "room": "101C",
    "doctor": "",
    "nurse": "Olivia Davis",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 76,
    "spo2": 98,
    "rr": 18,
    "bp": "116/76",
    "emotion": "Neutral"
  },
  {
    "id": "P007",
    "name": "Jessica Moore",
    "age": 38,
    "room": "102D",
    "doctor": "Dr. Lee",
    "nurse": "William Moore",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 77,
    "spo2": 99,
    "rr": 19,
    "bp": "117/77",
    "emotion": "Neutral"
  },
  {
    "id": "P008",
    "name": "David Taylor",
    "age": 55,
    "room": "103A",
    "doctor": "Dr. Patel",
    "nurse": "",
    "criticality": "Critical",
    "status": "ALERT",
    "hr": 128,
    "spo2": 91,
    "rr": 25,
    "bp": "158/103",
    "emotion": "Fear"
  },
  {
    "id": "P009",
    "name": "Ashley Anderson",
    "age": 23,
    "room": "104B",
    "doctor": "",
    "nurse": "Lucas Anderson",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 79,
    "spo2": 97,
    "rr": 17,
    "bp": "119/79",
    "emotion": "Neutral"
  },
  {
    "id": "P010",
    "name": "James Thomas",
    "age": 68,
    "room": "100C",
    "doctor": "Dr. Smith",
    "nurse": "Sarah Jenkins",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 80,
    "spo2": 98,
    "rr": 18,
    "bp": "120/80",
    "emotion": "Neutral"
  },
  {
    "id": "P011",
    "name": "Amanda Jackson",
    "age": 41,
    "room": "101D",
    "doctor": "Dr. Adams",
    "nurse": "Mike Ross",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 81,
    "spo2": 99,
    "rr": 19,
    "bp": "121/81",
    "emotion": "Neutral"
  },
  {
    "id": "P012",
    "name": "Matthew White",
    "age": 50,
    "room": "102A",
    "doctor": "",
    "nurse": "",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 82,
    "spo2": 96,
    "rr": 16,
    "bp": "122/82",
    "emotion": "Neutral"
  },
  {
    "id": "P013",
    "name": "Melissa Harris",
    "age": 31,
    "room": "103B",
    "doctor": "Dr. Patel",
    "nurse": "David Kim",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 83,
    "spo2": 97,
    "rr": 17,
    "bp": "123/83",
    "emotion": "Neutral"
  },
  {
    "id": "P014",
    "name": "Joseph Martin",
    "age": 59,
    "room": "104C",
    "doctor": "Dr. Garcia",
    "nurse": "Emma Wilson",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 84,
    "spo2": 98,
    "rr": 18,
    "bp": "124/84",
    "emotion": "Neutral"
  },
  {
    "id": "P015",
    "name": "John Doe",
    "age": 72,
    "room": "100D",
    "doctor": "",
    "nurse": "James Miller",
    "criticality": "Severe",
    "status": "ALERT",
    "hr": 110,
    "spo2": 99,
    "rr": 19,
    "bp": "125/70",
    "emotion": "Pain"
  },
  {
    "id": "P016",
    "name": "Jane Smith",
    "age": 46,
    "room": "101A",
    "doctor": "Dr. Adams",
    "nurse": "",
    "criticality": "Critical",
    "status": "ALERT",
    "hr": 136,
    "spo2": 89,
    "rr": 25,
    "bp": "166/96",
    "emotion": "Fear"
  },
  {
    "id": "P017",
    "name": "Robert Johnson",
    "age": 53,
    "room": "102B",
    "doctor": "Dr. Lee",
    "nurse": "William Moore",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 87,
    "spo2": 97,
    "rr": 17,
    "bp": "127/72",
    "emotion": "Neutral"
  },
  {
    "id": "P018",
    "name": "Emily Davis",
    "age": 30,
    "room": "103C",
    "doctor": "",
    "nurse": "Sophia Taylor",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 88,
    "spo2": 98,
    "rr": 18,
    "bp": "128/73",
    "emotion": "Neutral"
  },
  {
    "id": "P019",
    "name": "Michael Brown",
    "age": 62,
    "room": "104D",
    "doctor": "Dr. Garcia",
    "nurse": "Lucas Anderson",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 89,
    "spo2": 99,
    "rr": 19,
    "bp": "129/74",
    "emotion": "Neutral"
  },
  {
    "id": "P020",
    "name": "Sarah Wilson",
    "age": 35,
    "room": "100A",
    "doctor": "Dr. Smith",
    "nurse": "",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 90,
    "spo2": 96,
    "rr": 16,
    "bp": "110/75",
    "emotion": "Neutral"
  },
  {
    "id": "P021",
    "name": "William Miller",
    "age": 48,
    "room": "101B",
    "doctor": "",
    "nurse": "Mike Ross",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 91,
    "spo2": 97,
    "rr": 17,
    "bp": "111/76",
    "emotion": "Neutral"
  },
  {
    "id": "P022",
    "name": "Jessica Moore",
    "age": 39,
    "room": "102C",
    "doctor": "Dr. Lee",
    "nurse": "Nancy Drew",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 92,
    "spo2": 98,
    "rr": 18,
    "bp": "112/77",
    "emotion": "Neutral"
  },
  {
    "id": "P023",
    "name": "David Taylor",
    "age": 56,
    "room": "103D",
    "doctor": "Dr. Patel",
    "nurse": "David Kim",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 93,
    "spo2": 99,
    "rr": 19,
    "bp": "113/78",
    "emotion": "Neutral"
  },
  {
    "id": "P024",
    "name": "Ashley Anderson",
    "age": 24,
    "room": "104A",
    "doctor": "",
    "nurse": "",
    "criticality": "Critical",
    "status": "ALERT",
    "hr": 124,
    "spo2": 92,
    "rr": 25,
    "bp": "174/104",
    "emotion": "Fear"
  },
  {
    "id": "P025",
    "name": "James Thomas",
    "age": 69,
    "room": "100B",
    "doctor": "Dr. Smith",
    "nurse": "James Miller",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 70,
    "spo2": 97,
    "rr": 17,
    "bp": "115/80",
    "emotion": "Neutral"
  },
  {
    "id": "P026",
    "name": "Amanda Jackson",
    "age": 42,
    "room": "101C",
    "doctor": "Dr. Adams",
    "nurse": "Olivia Davis",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 71,
    "spo2": 98,
    "rr": 18,
    "bp": "116/81",
    "emotion": "Neutral"
  },
  {
    "id": "P027",
    "name": "Matthew White",
    "age": 51,
    "room": "102D",
    "doctor": "",
    "nurse": "William Moore",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 72,
    "spo2": 99,
    "rr": 19,
    "bp": "117/82",
    "emotion": "Neutral"
  },
  {
    "id": "P028",
    "name": "Melissa Harris",
    "age": 32,
    "room": "103A",
    "doctor": "Dr. Patel",
    "nurse": "",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 73,
    "spo2": 96,
    "rr": 16,
    "bp": "118/83",
    "emotion": "Neutral"
  },
  {
    "id": "P029",
    "name": "Joseph Martin",
    "age": 60,
    "room": "104B",
    "doctor": "Dr. Garcia",
    "nurse": "Lucas Anderson",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 74,
    "spo2": 97,
    "rr": 17,
    "bp": "119/84",
    "emotion": "Neutral"
  },
  {
    "id": "P030",
    "name": "John Doe",
    "age": 73,
    "room": "100C",
    "doctor": "",
    "nurse": "Sarah Jenkins",
    "criticality": "Severe",
    "status": "ALERT",
    "hr": 110,
    "spo2": 98,
    "rr": 18,
    "bp": "120/70",
    "emotion": "Pain"
  },
  {
    "id": "P031",
    "name": "Jane Smith",
    "age": 47,
    "room": "101D",
    "doctor": "Dr. Adams",
    "nurse": "Mike Ross",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 76,
    "spo2": 99,
    "rr": 19,
    "bp": "121/71",
    "emotion": "Neutral"
  },
  {
    "id": "P032",
    "name": "Robert Johnson",
    "age": 54,
    "room": "102A",
    "doctor": "Dr. Lee",
    "nurse": "",
    "criticality": "Critical",
    "status": "ALERT",
    "hr": 132,
    "spo2": 90,
    "rr": 25,
    "bp": "152/97",
    "emotion": "Fear"
  },
  {
    "id": "P033",
    "name": "Emily Davis",
    "age": 31,
    "room": "103B",
    "doctor": "",
    "nurse": "David Kim",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 78,
    "spo2": 97,
    "rr": 17,
    "bp": "123/73",
    "emotion": "Neutral"
  },
  {
    "id": "P034",
    "name": "Michael Brown",
    "age": 63,
    "room": "104C",
    "doctor": "Dr. Garcia",
    "nurse": "Emma Wilson",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 79,
    "spo2": 98,
    "rr": 18,
    "bp": "124/74",
    "emotion": "Neutral"
  },
  {
    "id": "P035",
    "name": "Sarah Wilson",
    "age": 36,
    "room": "100D",
    "doctor": "Dr. Smith",
    "nurse": "James Miller",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 80,
    "spo2": 99,
    "rr": 19,
    "bp": "125/75",
    "emotion": "Neutral"
  },
  {
    "id": "P036",
    "name": "William Miller",
    "age": 49,
    "room": "101A",
    "doctor": "",
    "nurse": "",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 81,
    "spo2": 96,
    "rr": 16,
    "bp": "126/76",
    "emotion": "Neutral"
  },
  {
    "id": "P037",
    "name": "Jessica Moore",
    "age": 40,
    "room": "102B",
    "doctor": "Dr. Lee",
    "nurse": "William Moore",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 82,
    "spo2": 97,
    "rr": 17,
    "bp": "127/77",
    "emotion": "Neutral"
  },
  {
    "id": "P038",
    "name": "David Taylor",
    "age": 57,
    "room": "103C",
    "doctor": "Dr. Patel",
    "nurse": "Sophia Taylor",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 83,
    "spo2": 98,
    "rr": 18,
    "bp": "128/78",
    "emotion": "Neutral"
  },
  {
    "id": "P039",
    "name": "Ashley Anderson",
    "age": 25,
    "room": "104D",
    "doctor": "",
    "nurse": "Lucas Anderson",
    "criticality": "Stable",
    "status": "Stable",
    "hr": 84,
    "spo2": 99,
    "rr": 19,
    "bp": "129/79",
    "emotion": "Neutral"
  },
  {
    "id": "P040",
    "name": "James Thomas",
    "age": 70,
    "room": "100A",
    "doctor": "Dr. Smith",
    "nurse": "",
    "criticality": "Critical",
    "status": "ALERT",
    "hr": 120,
    "spo2": 88,
    "rr": 25,
    "bp": "160/105",
    "emotion": "Fear"
  }
];
